name: hpack
version: 23.0.0
synopsis: An alternative format for Haskell packages
description: See README at <https://github.com/sol/hpack#readme>
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: sol/hpack
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >= 4.8 && < 5
  - bytestring
  - deepseq
  - directory
  - filepath
  - Glob
  - text
  - containers
  - unordered-containers
  - yaml
  - aeson >= 0.11
  - scientific
  - Cabal
  - pretty
  - bifunctors
  - cryptonite
  - transformers
  - http-types
  - http-client
  - http-client-tls

library:
  source-dirs: src
  exposed-modules:
    - Hpack
    - Hpack.Config
    - Hpack.Run
    - Hpack.Yaml

executable:
  main: Main.hs
  source-dirs: driver
  dependencies:
    - hpack

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - temporary
      - mockery >= 0.3
      - interpolate
